CREATE TABLE [dbo].[sales]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [ProductId] UNIQUEIDENTIFIER NOT NULL, 
    [SalesPrice] MONEY NOT NULL, 
    [TimeOfSale] DATETIME NULL
)
